version: '3.8'

services:
  flask:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flask_service
    ports:
      - "5000:5000"

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_service
    ports:
      - "3000:3000"
    depends_on:
      - flask

